### ISSUE TITLE
Server 500 error in review form

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#263]
I'm getting a number of 500 server errors in the template RUA. These have occurred so far when I:
- tried to add a field to review forms (e.g. http://template.rua.pm/manager/review-forms/form/2/add/field/). This seems to be a problem when adding help text. If the help text is not added then there is no error.
- added a new user
- submitted a proposal

The first 2 are not too urgent, but the proposal error means that I can't test the process fully.

**Comment by IoannisCleary** [comment]
@twakeford I fixed the first one. I tried submitting a proposal and a new user , there were no errors.

**Comment by twakeford** [comment]
@IoannisCleary  I still get a Server 500 error
![screen shot 2016-01-29 at 14 49 35](https://cloud.githubusercontent.com/assets/15159847/12678614/8cf8d1a4-c697-11e5-8b50-0d4b01fe9133.png)

I have added text in all fields and uploaded a file to the form, if that helps.

**Comment by IoannisCleary** [comment]
@twakeford  It seems to be related to the file upload field . If you don't upload a file, it works. 
I'll look into it

**Comment by IoannisCleary** [comment]
@twakeford the only 500 error left is the add user one. I completed all the fields and file uploading one and I don't get an error message. Could you give me the data that you entered that caused the error ?

**Comment by IoannisCleary** [comment]
@twakeford is the add new user page still causing a 500 error?

**Comment by twakeford** [comment]
nope - I just added Tom successfully to the template installation.
When I tried to copy the password the box in the right corner disappeared when I clicked on it = we still need to find a better way to provide editors with the password for people that they register.

**Comment by ajrbyers** [comment]
@IoannisCleary @twakeford its insecure and I hate it, but how about just emailing the password to the new user?

**Comment by IoannisCleary** [comment]
@ajrbyers the password is emailed.... "logic.send_new_user_ack(email_text, user, new_pass)"

**Comment by twakeford** [comment]
@ajrbyers  Can it now just be available to the editor on the screen somewhere? It is the temporary nature of the box that means it is hard to pass on when it is needed. Emailing the user isn't my preference, as it will mean that a reviewer will receive an email with login details potentially quite a long time before the editor actually sends them a review invitation

**Comment by ajrbyers** [comment]
@IoannisCleary isn't that when we change the owner? 

@twakeford okay, Im assigning this to myself for resolution.

**Comment by IoannisCleary** [comment]
@ajrbyers It's similar to that. We have the same thing in the manager.add_user view
